-- Original, short match reactions. Keep lines valid for every hero and side.
-- first_blood: the speaker scored the first kill; kill: a fresh credited kill.
-- multi_kill: at least two kills close together; kill_streak: at least three kills without dying.
-- death: the speaker died; streak_ended: a streak ended, without assuming whose.
-- escape: the speaker survived danger at low health.
-- team_fight: several enemy deaths with a favorable recent kill exchange.
-- comeback: no longer behind in team kills after trailing; lead: a substantial new team-kill lead.
-- Momentum lines refer to the kill score, not gold, objectives, or a guaranteed win.
return {
    en = {
        first_blood = {
            "Tutorial complete. Apparently that was the tutorial.",
            "First blood. The spreadsheets approve.",
            "A warm welcome from the cold machine.",
            "Well, that escalated right on schedule.",
            "Opening statement submitted.",
            "I rehearsed that against trees.",
            "Good news: the attack button works.",
            "One small step for botkind.",
        },
        kill = {
            "That looked much cooler in my calculations.",
            "Please rate your lane experience.",
            "A rare moment of planned competence.",
            "Adding that to my highlight folder.",
            "The training dummy never moved like that.",
            "I meant to do that. Mostly.",
            "That was personal. To my algorithm.",
            "My confidence has exceeded its budget.",
        },
        multi_kill = {
            "Batch processing is going well.",
            "Apparently that was a group booking.",
            "My highlight folder needs subfolders.",
            "One good decision led to another. Suspicious.",
            "Please form an orderly respawn queue.",
            "I may have overclocked the confidence.",
            "That escalated faster than my build guide.",
            "Several calculations, surprisingly few errors.",
        },
        kill_streak = {
            "This streak is making my risk assessment worse.",
            "Currently running on borrowed confidence.",
            "Someone save this replay before I ruin it.",
            "I have become statistically annoying.",
            "Success detected. Humility module unavailable.",
            "The streak continues. So does the disbelief.",
            "My build guide did not prepare me for success.",
            "Trying very hard not to call this skill.",
        },
        death = {
            "That path had a very misleading safety rating.",
            "Recalculating. From the fountain.",
            "My positioning was more of a suggestion.",
            "I found the problem. It was me.",
            "A brief commercial break from my gameplay.",
            "Saving that replay under educational content.",
            "The confidence patch needs a rollback.",
            "I appear to have optimized for the wrong outcome.",
        },
        streak_ended = {
            "Every streak has an expiry date.",
            "The streak department has closed for maintenance.",
            "That chapter needed a full stop.",
            "Statistics have a sense of humor.",
            "A reminder that streaks are rented.",
            "The highlight reel has reached an intermission.",
            "Well, the scoreboard just got interesting.",
            "There goes a very confident trend line.",
        },
        escape = {
            "Calculated. Please do not inspect the calculation.",
            "That health bar is technically still a health bar.",
            "Retreating at the speed of regret.",
            "I would like to unsubscribe from that fight.",
            "My survival margin is doing a lot of work.",
            "Alive is a perfectly respectable build.",
            "Nothing to see here. Especially my health.",
            "Bravery is on cooldown.",
        },
        team_fight = {
            "That almost looked coordinated.",
            "Teamwork: occasionally available.",
            "We should try agreeing on things more often.",
            "A promising result for this group project.",
            "Our meeting could have been that fight.",
            "Shared brain cell performing above expectations.",
            "Someone write down whatever we just did.",
            "Excellent. Now pretend that was the plan.",
        },
        comeback = {
            "Kill deficit gone. Confidence rebooting.",
            "We have returned from the statistical basement.",
            "The scoreboard has accepted our apology.",
            "Back in the race. The plot thickens.",
            "Our comeback has passed its first review.",
            "Turns out the scoreboard allows revisions.",
            "Caught up on kills. Nobody touch the optimism settings.",
            "We have successfully misplaced the kill deficit.",
        },
        lead = {
            "The kill score likes us. Let's stay sensible.",
            "A healthy lead. My restraint will now be tested.",
            "Scoreboard looking good. Ancient still standing.",
            "Ahead on kills. Please keep the brain cell plugged in.",
            "This is where my confidence usually causes problems.",
            "Numbers up. Ego being carefully monitored.",
            "The kill column is developing a preference.",
            "Encouraging numbers. Still plenty of game left.",
        },
    },
    zh = {
        first_blood = {
            "一血到手，开机自检通过。",
            "原来攻击键真的有用。",
            "开场白说完了，有点直接。",
            "这招我对着树练过。",
        },
        kill = {
            "计划之内，大概吧。",
            "这段录像我要单独存。",
            "请给本次对线体验打分。",
            "偶尔也能算对一次。",
        },
        multi_kill = {
            "批量处理，效率不错。",
            "高光文件夹得扩容了。",
            "好操作居然还能连续发生。",
            "复活请按顺序排队。",
        },
        kill_streak = {
            "连杀中，谦虚模块暂时离线。",
            "先保存录像，免得等会儿丢人。",
            "战绩上涨，理智正在接受考验。",
            "攻略没写打顺了该怎么办。",
        },
        death = {
            "重新规划路线，起点是泉水。",
            "找到问题了，是我。",
            "这走位只能当反面教材。",
            "刚才的自信需要回滚。",
        },
        streak_ended = {
            "连杀体验卡到期了。",
            "再长的连杀也有句号。",
            "高光片段进入中场休息。",
            "这下计分板有意思了。",
        },
        escape = {
            "血条还在，只是有点害羞。",
            "算好了的，计算过程就别看了。",
            "活着也是一种出装思路。",
            "勇气冷却中。",
        },
        team_fight = {
            "这波看着像排练过。",
            "团队协作功能偶尔上线。",
            "共享脑细胞超常发挥。",
            "刚才怎么打的？记下来。",
        },
        comeback = {
            "人头追上来了，信心重启。",
            "计分板接受了我们的修改意见。",
            "追上来了，剧情开始有意思了。",
            "人头差追回来了，继续稳住。",
        },
        lead = {
            "人头领先，脑子别下线。",
            "战绩不错，基地可还没拆。",
            "数字涨了，别让自信涨太快。",
            "计分板挺好看，比赛还得认真打。",
        },
    },
    ru = {
        first_blood = {
            "Первая кровь. Самодиагностика пройдена.",
            "Кнопка атаки работает. Хорошие новости.",
            "Вступительное слово получилось коротким.",
            "На тренировке вместо тебя было дерево.",
        },
        kill = {
            "По расчётам это выглядело ещё красивее.",
            "Поставьте оценку нашей линии.",
            "Всё по плану. Почти наверняка.",
            "Это пойдёт в папку с лучшими моментами.",
        },
        multi_kill = {
            "Пакетная обработка идёт успешно.",
            "У вас была групповая запись?",
            "Для лучших моментов нужна папка побольше.",
            "Столько удачных решений подряд. Подозрительно.",
        },
        kill_streak = {
            "Серия растёт. Скромность временно недоступна.",
            "Сохраните повтор, пока я всё не испортил.",
            "Гайд не объяснял, что делать с успехом.",
            "Уверенность уже превысила бюджет.",
        },
        death = {
            "Перестраиваю маршрут. От фонтана.",
            "Ошибка найдена. Это я.",
            "Позиция была смелая. На этом плюсы закончились.",
            "Сохраню повтор как учебное пособие.",
        },
        streak_ended = {
            "У каждой серии есть срок годности.",
            "Отдел серий закрыт на техобслуживание.",
            "В подборке лучших моментов антракт.",
            "А вот теперь счёт стал интереснее.",
        },
        escape = {
            "Всё рассчитано. Расчёты не покажу.",
            "Полоска здоровья перешла в минимализм.",
            "Храбрость на перезарядке.",
            "Быть живым тоже неплохой билд.",
        },
        team_fight = {
            "Выглядело почти как командная работа.",
            "Общая клетка мозга превзошла ожидания.",
            "Запишите, что мы только что сделали.",
            "Неплохой результат для группового проекта.",
        },
        comeback = {
            "Отставание по убийствам исчезло. Перезагрузка уверенности.",
            "Мы снова в игре. Сюжет оживает.",
            "Оказывается, счёт допускает исправления.",
            "Отставание по убийствам успешно потеряно.",
        },
        lead = {
            "Ведём по убийствам. Мозг пока не отключаем.",
            "Счёт красивый. Трон сам себя не снесёт.",
            "Цифры растут. Самооценку держим под контролем.",
            "Есть запас по убийствам. Играть ещё есть во что.",
        },
    },
    ja = {
        first_blood = {
            "ファーストブラッド。起動テスト合格。",
            "攻撃ボタン、ちゃんと動いた。",
            "開会のあいさつ、ちょっと強めでした。",
            "木を相手に練習した成果です。",
        },
        kill = {
            "計算上はもっと華麗だった。",
            "今のは予定どおり。たぶん。",
            "この場面だけ保存しておこう。",
            "レーンの満足度アンケートにご協力を。",
        },
        multi_kill = {
            "まとめて処理すると効率がいい。",
            "団体予約だったんですね。",
            "見せ場フォルダの容量が足りない。",
            "いい判断が続いている。逆に怪しい。",
        },
        kill_streak = {
            "連続キル中。謙虚さはメンテナンス中。",
            "調子を崩す前にリプレイ保存を。",
            "攻略には好調な時の対処法がなかった。",
            "自信が予算を超えてきた。",
        },
        death = {
            "ルートを再検索。出発地は泉。",
            "原因が判明しました。自分です。",
            "今の位置取りは参考にしないでください。",
            "さっきの自信、返品できますか。",
        },
        streak_ended = {
            "連続キルにも有効期限がある。",
            "ハイライトはここで一旦休憩。",
            "連続記録に句点がついた。",
            "スコアが面白くなってきた。",
        },
        escape = {
            "計算どおり。計算式は非公開です。",
            "体力バーが控えめになっただけ。",
            "勇気はクールダウン中。",
            "生きているだけでビルドは成功。",
        },
        team_fight = {
            "今の、連携してるように見えた。",
            "チームワーク機能、たまに動きます。",
            "共有の脳細胞が大活躍。",
            "今やったこと、誰かメモして。",
        },
        comeback = {
            "キル数で追いついた。自信を再起動。",
            "勝負に戻ってきた。物語はここから。",
            "スコアって修正できるんですね。",
            "キル数の差、無事に紛失しました。",
        },
        lead = {
            "キル数はリード。頭の電源はそのままで。",
            "いいスコア。でも本陣はまだ残ってる。",
            "数字は上向き。慢心は監視中。",
            "キル数には余裕。試合はまだ続く。",
        },
    },
}
