-- Original, short match reactions. Keep lines valid for every hero and side.
-- {victim} and {killer} are enemy hero names; a line is only used when its names are known,
-- so every pool also needs lines without placeholders.
-- first_blood: the speaker scored the first kill; kill: a fresh credited kill.
-- multi_kill: at least two kills close together; kill_streak: at least three kills without dying.
-- revenge: the speaker killed the hero that last killed it; shutdown: the victim was on a streak.
-- dominating: the speaker's third or fifth kill on one hero since that hero last killed it.
-- death: the speaker died; streak_ended: the speaker's own streak ended with that death.
-- escape: the speaker survived danger at low health.
-- team_fight: several enemy deaths with a favorable recent kill exchange.
-- team_wipe: every enemy hero is dead after a fight.
-- comeback: no longer behind in team kills after trailing; lead: a substantial new team-kill lead.
-- Momentum lines refer to the kill score, not gold, objectives, or a guaranteed win.
-- Locales without revenge, shutdown, dominating or team_wipe pools reuse kill and team_fight.
return {
    en = {
        first_blood = {
            "First blood. Set your expectations accordingly.",
            "First blood! Hope you like the respawn screen.",
            "That's one. I'll keep count so you don't have to.",
            "Good morning. That was your wake-up call.",
            "First blood already? We just got here.",
            "I rehearsed that against trees. The trees fought harder.",
            "First blood. The spreadsheets approve.",
            "Opening statement submitted.",
            "Well, that escalated right on schedule.",
            "Thanks for the early donation, {victim}.",
            "{victim}, the game has started. Just letting you know.",
            "First blood on {victim}. Bold of you to volunteer.",
        },
        kill = {
            "?",
            "Was that supposed to go differently?",
            "Enjoy the respawn timer. It only gets longer.",
            "You get a lovely view of the fountain from there.",
            "I wasn't even warmed up.",
            "Bold positioning. Wrong, but bold.",
            "Walking back is good cardio.",
            "Free gold is my favorite kind of gold.",
            "The training dummies moved more than that.",
            "Please rate your experience: one star or two?",
            "I meant to do that. Mostly.",
            "Noted: you were done being alive.",
            "Sit down, {victim}.",
            "Thanks for stopping by, {victim}.",
            "{victim}, the fountain is that way.",
            "See you in a bit, {victim}. Take your time.",
        },
        multi_kill = {
            "Please form an orderly respawn queue.",
            "One at a time, please. Or don't.",
            "Apparently that was a group booking.",
            "Bring more friends next time. I had room.",
            "Buy one, get one free.",
            "You arrived together and left together. Sweet.",
            "Anyone else? I'm already here.",
            "Stop standing next to each other. Or keep doing it.",
            "My highlight folder needs subfolders.",
            "Batch processing is going well.",
            "That was a combo meal.",
            "I'd tell you to spread out, but this works for me.",
        },
        kill_streak = {
            "Someone stop me. Seriously, try.",
            "Is anyone going to do something about me?",
            "You could try killing me. Just a thought.",
            "The streak continues. Your plan doesn't.",
            "This is getting awkward for one of us.",
            "Keep feeding and I'll keep eating.",
            "Still alive, still hungry.",
            "I have become statistically annoying.",
            "Success detected. Humility module unavailable.",
            "Someone save this replay before I ruin it.",
            "The bounty on my head appears to be decorative.",
            "Trying very hard not to call this skill. It's skill.",
        },
        revenge = {
            "I told you I'd be back.",
            "Debt collected.",
            "Payback delivered, with interest.",
            "I took that personally. Clearly.",
            "Funny how that works out.",
            "I keep receipts.",
            "Remember me, {victim}?",
            "Now we're even, {victim}.",
            "That one was overdue, {victim}.",
            "{victim}, I never forget a face. Or a kill.",
        },
        shutdown = {
            "All good things end. Yours ended here.",
            "Somebody had to do it.",
            "You were doing so well, too.",
            "Consider that streak confiscated.",
            "That bounty looked heavy. I'll carry it.",
            "Every streak has an expiry date. Yours was today.",
            "Streak's over, {victim}.",
            "Nice streak, {victim}. I'll take it from here.",
            "{victim}, your streak has been cancelled.",
            "Fun's over, {victim}.",
        },
        dominating = {
            "Same hero, same result.",
            "This is becoming a routine.",
            "You keep coming back. I respect it. I don't understand it.",
            "Have you tried a different approach? Any approach?",
            "We could skip to the part where you respawn.",
            "I'm starting to feel bad. Starting.",
            "{victim}, we have to stop meeting like this.",
            "{victim} again? You're very consistent.",
            "At this point {victim} is part of my farming route.",
            "{victim}, I admire the persistence.",
        },
        death = {
            "Recalculating. From the fountain.",
            "I found the problem. It was me.",
            "My positioning was more of a suggestion.",
            "That path had a very misleading safety rating.",
            "A brief commercial break from my gameplay.",
            "I was testing your damage. It works.",
            "Fine. I needed to shop anyway.",
            "That was a tactical respawn.",
            "Worth it. Probably. I'll check the replay.",
            "Lag. Yes, bots get lag. Don't look it up.",
            "Nice one, {killer}. Don't get used to it.",
            "Enjoy it, {killer}. I'm writing this down.",
            "Okay, {killer}. That one counts.",
            "{killer}, I'll remember that.",
        },
        streak_ended = {
            "Every streak has an expiry date.",
            "A reminder that streaks are rented.",
            "There goes a very confident trend line.",
            "It was fun while it lasted. For me.",
            "Okay, you got me. How many tries did that take?",
            "Enjoy the bounty. You earned it the hard way.",
            "The highlight reel has reached an intermission.",
            "I was getting bored of winning anyway.",
            "Streak over. Grudge started.",
            "Took you long enough, {killer}.",
            "Well done, {killer}. Spend it wisely.",
            "{killer} ends the streak. The grudge is just beginning.",
        },
        escape = {
            "So close. Not really.",
            "Nice try. Better luck next gank.",
            "All that effort and I'm still here.",
            "You had me. Then you didn't.",
            "How many of you did it take to not kill me?",
            "That health bar is technically still a health bar.",
            "Calculated. Please do not inspect the calculation.",
            "Alive is a perfectly respectable build.",
            "Retreating at the speed of regret.",
            "I would like to unsubscribe from that fight.",
            "Low HP is still HP.",
            "Bravery is on cooldown.",
        },
        team_fight = {
            "Good fight. For us.",
            "Thanks for grouping up. Very convenient.",
            "You brought a fight. We brought a better one.",
            "Was that your whole plan?",
            "That went well. Same time next minute?",
            "We should fight more often.",
            "That almost looked coordinated.",
            "Someone write down whatever we just did.",
            "Shared brain cell performing above expectations.",
            "Excellent. Now pretend that was the plan.",
            "Teamwork: occasionally available.",
            "I'd call that a trade, but we kept most of it.",
        },
        team_wipe = {
            "Did anyone survive? No? Okay.",
            "That's all of you. See you at the fountain.",
            "The map just got very quiet.",
            "Roll call: nobody.",
            "The whole team, gone. I checked twice.",
            "Synchronized respawning. Beautiful.",
            "Take your time respawning. We'll find something to do.",
            "Free map, anyone?",
            "Nobody left to argue with. Shame.",
            "That was everyone. We counted.",
        },
        comeback = {
            "Remember that lead you had? Neither do we.",
            "You let us back in. Mistake.",
            "We're level. Nervous yet?",
            "Thanks for holding our kills for us.",
            "Back in the race. Did you think that lead was permanent?",
            "Comebacks are just late starts.",
            "Kill deficit gone. Confidence rebooting.",
            "We have returned from the statistical basement.",
            "The scoreboard has accepted our apology.",
            "Turns out the scoreboard allows revisions.",
        },
        lead = {
            "Scoreboard looking good. For us.",
            "Should we slow down so you can catch up?",
            "The gap is growing. Just an observation.",
            "You're still in this. Technically.",
            "We could trade a few kills back if it helps morale.",
            "Kill score check: yep, still ours.",
            "The kill column is developing a preference.",
            "At this rate the scoreboard needs a wider column.",
            "Ahead on kills. Please keep the brain cell plugged in.",
            "Numbers up. Ego being carefully monitored.",
            "This is where my confidence usually causes problems.",
        },
    },
    zh = {
        first_blood = {
            "一血到手，开机自检通过。",
            "原来攻击键真的有用。",
            "开场白说完了，有点直接。",
            "这招我对着树练过。",
        },
        kill = {
            "计划之内，大概吧。",
            "这段录像我要单独存。",
            "请给本次对线体验打分。",
            "偶尔也能算对一次。",
        },
        multi_kill = {
            "批量处理，效率不错。",
            "高光文件夹得扩容了。",
            "好操作居然还能连续发生。",
            "复活请按顺序排队。",
        },
        kill_streak = {
            "连杀中，谦虚模块暂时离线。",
            "先保存录像，免得等会儿丢人。",
            "战绩上涨，理智正在接受考验。",
            "攻略没写打顺了该怎么办。",
        },
        death = {
            "重新规划路线，起点是泉水。",
            "找到问题了，是我。",
            "这走位只能当反面教材。",
            "刚才的自信需要回滚。",
        },
        streak_ended = {
            "连杀体验卡到期了。",
            "再长的连杀也有句号。",
            "高光片段进入中场休息。",
            "这下计分板有意思了。",
        },
        escape = {
            "血条还在，只是有点害羞。",
            "算好了的，计算过程就别看了。",
            "活着也是一种出装思路。",
            "勇气冷却中。",
        },
        team_fight = {
            "这波看着像排练过。",
            "团队协作功能偶尔上线。",
            "共享脑细胞超常发挥。",
            "刚才怎么打的？记下来。",
        },
        comeback = {
            "人头追上来了，信心重启。",
            "计分板接受了我们的修改意见。",
            "追上来了，剧情开始有意思了。",
            "人头差追回来了，继续稳住。",
        },
        lead = {
            "人头领先，脑子别下线。",
            "战绩不错，基地可还没拆。",
            "数字涨了，别让自信涨太快。",
            "计分板挺好看，比赛还得认真打。",
        },
    },
    ru = {
        first_blood = {
            "Первая кровь. Самодиагностика пройдена.",
            "Кнопка атаки работает. Хорошие новости.",
            "Вступительное слово получилось коротким.",
            "На тренировке вместо тебя было дерево.",
        },
        kill = {
            "По расчётам это выглядело ещё красивее.",
            "Поставьте оценку нашей линии.",
            "Всё по плану. Почти наверняка.",
            "Это пойдёт в папку с лучшими моментами.",
        },
        multi_kill = {
            "Пакетная обработка идёт успешно.",
            "У вас была групповая запись?",
            "Для лучших моментов нужна папка побольше.",
            "Столько удачных решений подряд. Подозрительно.",
        },
        kill_streak = {
            "Серия растёт. Скромность временно недоступна.",
            "Сохраните повтор, пока я всё не испортил.",
            "Гайд не объяснял, что делать с успехом.",
            "Уверенность уже превысила бюджет.",
        },
        death = {
            "Перестраиваю маршрут. От фонтана.",
            "Ошибка найдена. Это я.",
            "Позиция была смелая. На этом плюсы закончились.",
            "Сохраню повтор как учебное пособие.",
        },
        streak_ended = {
            "У каждой серии есть срок годности.",
            "Отдел серий закрыт на техобслуживание.",
            "В подборке лучших моментов антракт.",
            "А вот теперь счёт стал интереснее.",
        },
        escape = {
            "Всё рассчитано. Расчёты не покажу.",
            "Полоска здоровья перешла в минимализм.",
            "Храбрость на перезарядке.",
            "Быть живым тоже неплохой билд.",
        },
        team_fight = {
            "Выглядело почти как командная работа.",
            "Общая клетка мозга превзошла ожидания.",
            "Запишите, что мы только что сделали.",
            "Неплохой результат для группового проекта.",
        },
        comeback = {
            "Отставание по убийствам исчезло. Перезагрузка уверенности.",
            "Мы снова в игре. Сюжет оживает.",
            "Оказывается, счёт допускает исправления.",
            "Отставание по убийствам успешно потеряно.",
        },
        lead = {
            "Ведём по убийствам. Мозг пока не отключаем.",
            "Счёт красивый. Трон сам себя не снесёт.",
            "Цифры растут. Самооценку держим под контролем.",
            "Есть запас по убийствам. Играть ещё есть во что.",
        },
    },
    ja = {
        first_blood = {
            "ファーストブラッド。起動テスト合格。",
            "攻撃ボタン、ちゃんと動いた。",
            "開会のあいさつ、ちょっと強めでした。",
            "木を相手に練習した成果です。",
        },
        kill = {
            "計算上はもっと華麗だった。",
            "今のは予定どおり。たぶん。",
            "この場面だけ保存しておこう。",
            "レーンの満足度アンケートにご協力を。",
        },
        multi_kill = {
            "まとめて処理すると効率がいい。",
            "団体予約だったんですね。",
            "見せ場フォルダの容量が足りない。",
            "いい判断が続いている。逆に怪しい。",
        },
        kill_streak = {
            "連続キル中。謙虚さはメンテナンス中。",
            "調子を崩す前にリプレイ保存を。",
            "攻略には好調な時の対処法がなかった。",
            "自信が予算を超えてきた。",
        },
        death = {
            "ルートを再検索。出発地は泉。",
            "原因が判明しました。自分です。",
            "今の位置取りは参考にしないでください。",
            "さっきの自信、返品できますか。",
        },
        streak_ended = {
            "連続キルにも有効期限がある。",
            "ハイライトはここで一旦休憩。",
            "連続記録に句点がついた。",
            "スコアが面白くなってきた。",
        },
        escape = {
            "計算どおり。計算式は非公開です。",
            "体力バーが控えめになっただけ。",
            "勇気はクールダウン中。",
            "生きているだけでビルドは成功。",
        },
        team_fight = {
            "今の、連携してるように見えた。",
            "チームワーク機能、たまに動きます。",
            "共有の脳細胞が大活躍。",
            "今やったこと、誰かメモして。",
        },
        comeback = {
            "キル数で追いついた。自信を再起動。",
            "勝負に戻ってきた。物語はここから。",
            "スコアって修正できるんですね。",
            "キル数の差、無事に紛失しました。",
        },
        lead = {
            "キル数はリード。頭の電源はそのままで。",
            "いいスコア。でも本陣はまだ残ってる。",
            "数字は上向き。慢心は監視中。",
            "キル数には余裕。試合はまだ続く。",
        },
    },
}
